#cloud-config

# Install additional packages on first boot
#
# Default: none
#
# if packages are specified, this apt_update will be set to true
#
# packages may be supplied as a single package name or as a list
# with the format [<package>, <version>] wherein the specifc
# package version will be installed.
package_update: true
packages:
  - docker.io
runcmd:
  - [ sh, -c, echo "=========hello world'=========" ]